
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 5.0
      #dotnet: latest - Latest resolve to 3.1, check this issue https://github.com/aws/aws-codebuild-docker-images/issues/414
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore AWSDockerCICD/AWSDockerCICD.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build AWSDockerCICD/AWSDockerCICD.csproj
      - echo Test started on `date`
      - dotnet test AWSDockerCICD/AWSDockerCICD.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 -o ./ AWSDockerCICD/AWSDockerCICD.csproj
      
artifacts:
  files:
    - ./**/*
